version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"

  frontend:
    build:
      context: ./vending-machine-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: alipetek
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
